### ISSUE TITLE
Wallet connection issues

### ISSUE THREAD

**Issue by DarkGhost7** [iearn-finance/iearn-finance#100]
Argent with walletconnect not working, was working a week ago now giving the following error "index.ts:181 Uncaught (in promise) TypeError: this.send is not a function" right after connecting and not working afterwards.

If you're a user please leave you feed back of issues in the format
{wallet used}
{which connection method: (trustwallet / walletconnect ect}
{which os: android, ios, pc, mac}
{error msg, picture if you have one}

**Comment by PandaWhisperer** [comment]
I have this issue on the following configurations:

- Safari (MacOS) with Coinbase Wallet (iOS) using WalletLink
- Coinbase Wallet (iOS) solo (unsing the built-in browser)
- Opera Touch (iOS) using the built-in crypto wallet

**Comment by ShadeUndertree** [comment]
The site also does not load in Coinbase Wallet's built-in browser for me either.

Coinbase Wallet
Built-in Browser
iOS
![image](https://user-images.githubusercontent.com/72354637/95028967-69b11100-0659-11eb-9263-5bcc3f2afb34.png)

**Comment by CryptoRenegade** [comment]
I'm having the same issue with Trust Wallet as well. 

![Screenshot_20201004-200452~2](https://user-images.githubusercontent.com/72366096/95032449-99c3d880-0688-11eb-9992-16562b7159a3.png)

**Comment by tectumor** [comment]
Same issue with trust wallet both from mobile (iOS) and pc (Windows). On mobile I have used brave, safari, and chrome, on pc I have used brave, chrome, firefox. Nothing works.

**Comment by TransmissionsDev** [comment]
Downgrading to web3 version `^1.2.11` along with forcing a resolution for `"@walletconnect/web3-provider": "^1.3.1"` fixes this issue.
