### ISSUE TITLE
Include "Strategy rewards" disclaimer on Vaults page

### ISSUE THREAD

**Issue by WrongNebula** [iearn-finance/iearn-finance#106]
Improvement suggestion:

Include a "Strategy rewards" disclaimer at the bottom of the vaults page that explain how we reward strategists. A call to action for people to write strategies for Yearn per se.

[Example on NEAR protocol website](https://twitter.com/thibauld/status/1316182347943944192?s=21)

![EkQEnfFXcAAKHrY](https://user-images.githubusercontent.com/72853808/95955578-b63cdf00-0e05-11eb-9e61-9563de6d7b94.png)

**Comment by wirjo** [comment]
I like this idea - is there docs on what the rewards are? If not, it can link to a new page in the docs and incorporate @x48-crypto starter pack on https://gov.yearn.finance/t/request-for-knowledge-base-howto-learning-steps-for-becoming-a-strategy-writer/7007
