### ISSUE TITLE
Add team page

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [iearn-finance/iearn-finance#107]
https://gov.yearn.finance/t/proposal-poll-create-a-yearn-team-page-where-we-can-see-what-both-paid-and-volunteering-individuals-are-handling-in-the-ecosystem/6945

It should have a column for contact data, like email, Twitter and whatnot. Please don't make me install npm and who knows what else. I don't want to do this. :(

I'm hoping someone will self-assign for this and implement.

**Comment by wirjo** [comment]
Happy to help with this, it should probably link to a docs page though? Are these the team members?

yfi.banteg.eth
yfi.milkyklim.eth
tracheopteryx.eth
oniichan.eth
andrecronje.eth
substreight.eth
lux.eth

**Comment by x48-crypto** [comment]
September grants:

https://gov.yearn.finance/t/september-grants-announcement/7044
