### ISSUE TITLE
Warn Metamask user if he's not on Ethereum mainnet

### ISSUE THREAD

**Issue by WrongNebula** [iearn-finance/iearn-finance#111]
Currently if you open ygov and your Metamask is set to another network (testnet or custom RPC) it gives the following error:

![Screenshot 2020-10-17 at 11 55 24](https://user-images.githubusercontent.com/72853808/96333001-09b26580-1070-11eb-9329-22f0a517c06b.png)

It's also buggy with yearn.

It would be good to detect if the user is on Ethereum mainnet, if not, show a warning message.

**Comment by wirjo** [comment]
@x48-crypto I just did a PR to fix this bug, but could be a waste of time for such a small edge case. ROI on effort is not great but did it anyways to learn about `web3`!

**Comment by x48-crypto** [comment]
Decided not to change this now since this area is high risk and relatively low reward. We can do something similar on V2 UI instead.
