### ISSUE TITLE
Max Balance Rounding Issue

### ISSUE THREAD

**Issue by divThis** [iearn-finance/iearn-finance#12]
When attempting to deposit 100% of my DAI balance that has a large float value, the balance is rounded up to the nearest 8th decimal. In my case, I have a balance of 2.438169309543077043 DAI (as taken from Etherscan). When clicking my "balance" or "100%", a value of 2.43816931 (rounded up) is inserted into the earn box. When clicking "Earn", the value box is outlined in red indicating that it is more than my balance.

One potential fix would be to display the rounded value, but store the full balance in a hidden input and used it for the transaction. Right now, the only workaround seems to be to manually round down and deposit less (albeit very slightly less) than 100% of the balance.

**Comment by KadenZipfel** [comment]
https://github.com/iearn-finance/iearn-finance/pull/15

**Comment by 1Crazymoney** [comment]
How can I help?

**Comment by antonnell** [comment]
Closed by #15
