### ISSUE TITLE
Add prominent UI for deposit disabled vaults

### ISSUE THREAD

**Issue by franklin501** [iearn-finance/iearn-finance#125]
The Chainlink Vault is not scheduled to be re-opened any time soon, if at all. Since it will not be operational it should be removed, as it is causing confusion among end-users. Instead, they can use the aLINK vault.

Action: Remove Chainlink vault from the web repository (yVaults) page.

**Comment by x48-crypto** [comment]
If we remove disabled vaults from the UI users will not longer be able to withdraw.

@wirjo came up with a good alternative here: increase prominence of disabled vaults in the UI.
