### ISSUE TITLE
CI build fails with npm build errors

### ISSUE THREAD

**Issue by listonjesse** [iearn-finance/iearn-finance#153]
Creating an optimized production build...

Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Failed to compile.

./src/stores/store.jsx
  Line 1328:26:  Expected '!==' and instead saw '!='  eqeqeq
  Line 1333:26:  Expected '!==' and instead saw '!='  eqeqeq

./src/components/home/home.jsx
  Line 212:25:  'location' is assigned a value but never used  no-unused-vars

./src/components/apr/apr.jsx
  Line 296:20:  Expected to return a value in arrow function  array-callback-return
  Line 316:22:  Expected to return a value in arrow function  array-callback-return
  Line 335:20:  Expected to return a value in arrow function  array-callback-return
  Line 357:20:  Expected to return a value in arrow function  array-callback-return

./src/components/vault/vault.jsx
  Line 727:254:  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank

**Comment by x48-crypto** [comment]
```
commit 419940d4c1ace6e5c96adf2ccdfd69a1616eca08
Author: Jesse Liston <listonjesse@yahoo.com>
Date:   Sun Oct 25 08:43:17 2020 -0700

    fix: minor fixes so build passes on CI (#152)
```

```
commit 5cf357dcf3b0e7cd58584c0cba0bf65d72a0a745 (HEAD -> develop, origin/develop)
Author: x48 <70453354+x48-crypto@users.noreply.github.com>
Date:   Sun Oct 25 10:56:33 2020 -0500

    ci: fix build error (#154)
```
