### ISSUE TITLE
Re-arrange order of yVaults

### ISSUE THREAD

**Issue by franklin501** [iearn-finance/iearn-finance#156]
The current layout of the yVaults appears to be in an arbitrary order based on date added. This suggested change re-orders the yVaults to be in a logical order by importance/usage by end-user, and also groups them together by type. 

Please re-arrange the order of the yVaults in this manner:

1) curve.fi/3pool (highest ROI currently)
2) curve.fi/ypool (flagship and initial vault, despite current low ROI)
3) curve.fi/busd
4) curve.fi/sBTC
5) yETH (remove the WETH vault in the web repository. Logic down below).
6) yYFI
7) yDAI
8) yTUSD
8) yUSDC
9) yUSDT
10) GUSD
11) aLINK
12) yLINK (Remove).

WETH: Functionally the WETH and ETH vaults do the same thing. ETH is converted into WETH so that it can be used in the MakerDAO system to mint DAI. For the end-user there is no difference between these two vaults. But for less sophisticated users, it is confusing, why are there two vaults? Some people do not know the difference between WETH and ETH, but they all are aware of the "ETH yVault". Since they both do the same thing, and in an effort to reduce redundancy and clutter. Remove the WETH vault from the web repository. I believe the yETH vault (and web repository) will accept both ETH and WETH, and if a user deposits WETH it doesn't need to wrap it since it is already wrapped. 

yLINK: Please remove this vault. There is no ETA on when it will be opened, and people keep asking about it. Remove the vault from the web repository so we stop getting questions. Simiarly as above aLINK and yLINK vaults are functionally the same, if someone wants to deposit LINK they can deposit aLINK into the respective vault. 

https://yearn.finance/vaults

**Comment by x48-crypto** [comment]
If we removed the yLINK vault users would not have an easy way to withdraw funds

**Comment by milkyklim** [comment]
Put inactive vaults to the bottom, keep ordering as above and remove nothing.

**Comment by x48-crypto** [comment]
```
commit be70945ddd2cdc1cc11e6ea220cf10215de303fb (HEAD -> develop, origin/develop, origin/HEAD)
Author: Mehran Hydary <mehranhydary@users.noreply.github.com>
Date:   Tue Oct 27 19:52:33 2020 -0400

    refactor: change vault ordering. move inactive vaults to the bottom (#171)
```
