### ISSUE TITLE
Broken link on yearn.finance/vaults

### ISSUE THREAD

**Issue by vany365** [iearn-finance/iearn-finance#169]
yearn.finance/vaults

The "learn more" button under "Strategy Rewards" takes you to a broken link: https://docs.yearn.finance/how-to-guides/how-to-contribute-a-yvault-strategy/

The link should be: https://docs.yearn.finance/how-to-guides/how-to-participate-in-a-yvault

**Comment by x48-crypto** [comment]
```
commit a048550b5d00b7f2f7aab9743668d90fa5fff33c (HEAD -> develop, origin/develop)
Author: x48 <x48114@protonmail.com>
Date:   Tue Oct 27 18:44:00 2020 -0500

    fix: fix broken link on vaults page
```
