### ISSUE TITLE
GUSD vault shows incorrect APY and misleads users

### ISSUE THREAD

**Issue by listonjesse** [iearn-finance/iearn-finance#177]

**Comment by milkyklim** [comment]
#176 is not working unfortunately, can you review and resubmit?

**Comment by listonjesse** [comment]
Weird, it works for me:
![image](https://user-images.githubusercontent.com/7820952/97723116-a9b4b980-1a88-11eb-9612-e1b14a5a34d3.png)

Perhaps the CDN cache wasn't invalidated properly when you first checked? (Though the CI pipeline attempts to invalidate it)

**Comment by listonjesse** [comment]
Turns out if the yGUSD balance is greater than 0, then there is a visual issue:
![image](https://user-images.githubusercontent.com/7820952/97731164-0b2d5600-1a92-11eb-96bd-6553938c4be9.png)

THank you for catching that for me @milkyklim
