### ISSUE TITLE
Zap submit button does not appear

### ISSUE THREAD

**Issue by fameal** [iearn-finance/iearn-finance#85]
In Zap page, when you have DAI, the submit button does not appear. You can only make appear when you change the value in the combo box.

<img width="1436" alt="Screen Shot 2020-09-18 at 15 02 17" src="https://user-images.githubusercontent.com/839844/93630424-6dd60100-f9c0-11ea-8938-3bb1eed8d433.png">

**Comment by milkyklim** [comment]
1. Does it appear if you reload the page? 
2. Does it appear if you click 25%/50%/...?

**Comment by fameal** [comment]
1. No
2. No

The problem is when you change the "I have symbol". Is populated the "I want" bombo without make the "Submit" button appear. If you open the combo box and select and option, it appears.

**Comment by wirjo** [comment]
Attempted a fix here. There is complicated logic to show the default option which doesn't trigger the `onChange` event so the simple fix is to remove it and let the user choose the option #120

**Comment by x48-crypto** [comment]
Discussed this with @wirjo and tested locally. The deleted code is trying to predict what user the end user wants to use for the secondary zap item. The deleted code is broken (even if we fix the render error here there are more issues to fix) and is probably not worth fixing at this point. The solution is to let the user pick the secondary zap item from the list of approved tokens.
