### ISSUE TITLE
Fix overlapping columns

### ISSUE THREAD

**Issue by milkyklim** [iearn-finance/iearn-finance#88]
> Hey guys, not really a bug but the current strategy column overlaps with the total value holdings column on a 13inch laptop:

![image](https://user-images.githubusercontent.com/10698619/93886480-c3265100-fce5-11ea-9fb3-4fb7ef2f751b.png)

> Its not an issue on larger screens, but was wondering if we could fix this somehow? Maybe by just stripping away the ‘Strategy’ Prefix from each strategy? (guess that would give enough space even for 13inch screens)

ref: https://gov.yearn.finance/t/yearn-interaction-feedback-bugs/1321/6

**Comment by kmeraz** [comment]
Hopefully this is a solution that everyone can agree with https://github.com/iearn-finance/iearn-finance/pull/91
