### ISSUE TITLE
Total Earnings showing Deposits in the UI instead of earnings from yearn.tools

### ISSUE THREAD

**Issue by listonjesse** [iearn-finance/iearn-finance#93]
Here is the yearn vault UI:
![image](https://user-images.githubusercontent.com/7820952/94166193-e107c900-fe3f-11ea-9e86-468924b9400a.png)

Notice how Total Earnings is equal to Deposits, which is around 983.36

Here is the result from using yearn.tools on this account:
`  {
    "vaultAddress": "0x5dbcf33d8c2e976c6b560249878e6f1491bca25c",
    "totalDeposits": "983363199999999999999",
    "totalWithdrawals": "0",
    "totalTransferredIn": "0",
    "totalTransferredOut": "0",
    "depositedShares": "914167889107499533658",
    "depositedAmount": "1006254407763697324422",
    "earnings": "22.89120776369732442298"
  },`

Earnings here is ~22.89120776, not the 983.36 which is shown in the UI.

@antonnell, this [line of code](https://github.com/iearn-finance/iearn-finance/blob/master/src/components/vault/asset.jsx#L244) seems like it would use the earnings. This change seems like it is deployed, do you know any reason why my earnings on the website would show up differently on the yearn UI vs the yearn.tools API?

**Comment by x48-crypto** [comment]
I fixed this issue upstream (in the yearn.tools API) and this bug can now be closed.
I was previously normalizing vault earnings in the API response and now I do not.

https://github.com/yearn-integrations/api/commit/7c2de4a4c9b4c3471186665d1a5ee4a66084d66c

```
commit 7c2de4a4c9b4c3471186665d1a5ee4a66084d66c (HEAD -> main, origin/main)
Author: x48 <x48114@protonmail.com>
Date:   Thu Sep 24 19:59:50 2020 -0500

    Fixes vault earnings issue. Do not divide by 10**18.
```

**Comment by listonjesse** [comment]
Thanks!
