### ISSUE TITLE
Expanding a vault's dropdown before the vault deposit amount loads causes statistics to show as NaN

### ISSUE THREAD

**Issue by listonjesse** [iearn-finance/iearn-finance#94]
Repro:

1. Open https://yearn.finance/vaults
2. Immediately click a vault (with which you have a deposit balance) before the deposit balance loads and shows up

Issue:
![image](https://user-images.githubusercontent.com/7820952/94167968-faaa1000-fe41-11ea-9a59-df8744ea2778.png)
Statistics load with NaN, but Strategy details, APY, and Deposit Balance show up fine. 

![image](https://user-images.githubusercontent.com/7820952/94168133-2c22db80-fe42-11ea-8c0b-38cc76737763.png)

From the console, there seems to be a TypeError in the request to api.yearn.tools.

This only repros if you click a vault and open its drop down before the Deposit Balance and APY load.

**Comment by listonjesse** [comment]
This doesn't seem to repro anymore, so I am fine to close it if y'all want

**Comment by x48-crypto** [comment]
@listonjesse I increased the function timeout upstream. This should increase reliability.

**Comment by listonjesse** [comment]
@x48-crypto Makes sense to me. Thanks again!
