### ISSUE TITLE
Enable "Claim Rewards" button on the Staking Contract

### ISSUE THREAD

**Issue by DeFiGod1** [iearn-finance/iearn-finance#98]
A new YIP passed that allows governance stakers to claim rewards without having voted recently. The rewards can be claimed directly from etherscan, but the button on the UI is still greyed out. Can this button be enabled?

![image](https://user-images.githubusercontent.com/71345826/94446683-f732c380-0176-11eb-95f3-b516fbd23bf6.png)

**Comment by antonnell** [comment]
@DeFiGod1 

That functionality is on the ygov repository.

A PR was submitted for this and it was merged in 4 days ago.
https://github.com/iearn-finance/ygov-finance/pull/23

I don't control deployments, so not 100% sure when it will go live.
